'use client';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

export { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
export { library } from '@fortawesome/fontawesome-svg-core';

import {
  faChartBar,
  faLink,
  faShoppingCart,
  faChartLine,
  faGift,
  faCog,
  faBook,
  faBell,
  faUser,
  faCoins,
  faBars,
  faTimes,
  faComment,
  faChevronLeft,
  faChevronRight,
  faLightbulb,
  faCalendarDays,
  faImages,
  faTrash,
  faEdit,
  faPaperPlane,
  faRotateRight,
  faWandMagicSparkles,
  faPlus,
  faClock,
  faChevronUp,
  faChevronDown,
  faCheck,
  faDownload,
  faUpload,
  faSquarePlus,
  faSearch,
  
  faMicrophone,
  faEllipsisVertical,
  faFilter,
  faFileLines,
  faArrowRotateLeft,
  faStop,
  faHeart,
  faShare,
  faChartSimple,
  faArrowUp,
  faArrowDown,
  faUsers,
  faCalendarCheck,
  faPlay
} from '@fortawesome/free-solid-svg-icons';

import { library } from '@fortawesome/fontawesome-svg-core';

library.add(
  faChartBar,
  faLink,
  faShoppingCart,
  faChartLine,
  faGift,
  faCog,
  faBook,
  faBell,
  faUser,
  faCoins,
  faPlus,
  faBars,
  faTimes,
  faComment,
  faChevronLeft,
  faChevronRight,
  faLightbulb,
  faCalendarDays,
  faImages,
  faTrash,
  faEdit,
  faPaperPlane,
  faRotateRight,
  faWandMagicSparkles,
  faPlus,
  faClock,
  faChevronUp,
  faChevronDown,
  faCheck,
  faDownload,
  faUpload,
  faSquarePlus,
  faSearch,
  faMicrophone,
  faEllipsisVertical,
  faFilter,
  faFileLines,
  faArrowRotateLeft,
  faStop,
  faHeart,
  faShare,
  faChartSimple,
  faArrowUp,
  faArrowDown,
  faUsers,
  faCalendarCheck,
  faPlay
);
